"""phase3: inventory ledger and locations

Revision ID: 2a1f3abe4c59
Revises: 514a93d3f54c
Create Date: 2026-08-27 20:48:31.318424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1f3abe4c59'
down_revision: Union[str, Sequence[str], None] = '514a93d3f54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_location_business_name'),
    sa.UniqueConstraint('business_id', 'slug', name='uq_location_business_slug')
    )
    op.create_index('ix_locations_business_id', 'locations', ['business_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_business_created', 'inventory_movements', ['business_id', 'created_at'], unique=False)
    op.create_index('ix_inventory_movements_business_id', 'inventory_movements', ['business_id'], unique=False)
    op.create_index('ix_inventory_movements_business_product', 'inventory_movements', ['business_id', 'product_id'], unique=False)
    op.create_index('ix_inventory_movements_business_type', 'inventory_movements', ['business_id', 'type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index('ix_inventory_movements_device_id', 'inventory_movements', ['device_id'], unique=False)
    op.create_index('ix_inventory_movements_location_id', 'inventory_movements', ['location_id'], unique=False)
    op.create_index('ix_inventory_movements_product_id', 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_devices_location_id'), 'devices', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_location_id'), table_name='devices')
    op.drop_index('ix_inventory_movements_product_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_location_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_device_id', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_business_type', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_business_product', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_business_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_business_created', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_locations_business_id', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
