"""phase2: core entities

Revision ID: 514a93d3f54c
Revises: bf9a8c4afbd5
Create Date: 2026-08-27 20:27:48.550043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514a93d3f54c'
down_revision: Union[str, Sequence[str], None] = 'bf9a8c4afbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('default_warranty_months', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_category_business_name'),
    sa.UniqueConstraint('business_id', 'slug', name='uq_category_business_slug')
    )
    op.create_index('ix_categories_business_id', 'categories', ['business_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_business_id', 'customers', ['business_id'], unique=False)
    op.create_index('ix_customers_business_phone', 'customers', ['business_id', 'phone'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_business_id', 'suppliers', ['business_id'], unique=False)
    op.create_index('ix_suppliers_business_name', 'suppliers', ['business_id', 'name'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('imei', sa.String(length=30), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'serial_number', name='uq_device_business_serial')
    )
    op.create_index('ix_devices_business_id', 'devices', ['business_id'], unique=False)
    op.create_index('ix_devices_business_imei', 'devices', ['business_id', 'imei'], unique=False)
    op.create_index('ix_devices_business_serial', 'devices', ['business_id', 'serial_number'], unique=False)
    op.create_index('ix_devices_category_id', 'devices', ['category_id'], unique=False)
    op.create_index('ix_devices_status', 'devices', ['status'], unique=False)
    op.create_index('ix_devices_supplier_id', 'devices', ['supplier_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=False),
    sa.Column('unit_of_measurement', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('product_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_product_business_sku')
    )
    op.create_index('ix_products_business_barcode', 'products', ['business_id', 'barcode'], unique=False)
    op.create_index('ix_products_business_id', 'products', ['business_id'], unique=False)
    op.create_index('ix_products_business_name', 'products', ['business_id', 'name'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_supplier_id', 'products', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_supplier_id', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_business_name', table_name='products')
    op.drop_index('ix_products_business_id', table_name='products')
    op.drop_index('ix_products_business_barcode', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_devices_supplier_id', table_name='devices')
    op.drop_index('ix_devices_status', table_name='devices')
    op.drop_index('ix_devices_category_id', table_name='devices')
    op.drop_index('ix_devices_business_serial', table_name='devices')
    op.drop_index('ix_devices_business_imei', table_name='devices')
    op.drop_index('ix_devices_business_id', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_suppliers_business_name', table_name='suppliers')
    op.drop_index('ix_suppliers_business_id', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_customers_business_phone', table_name='customers')
    op.drop_index('ix_customers_business_id', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_categories_business_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
